[workspace]
authors = ["Tim <timcash@gmail.com>"]
channels = ["conda-forge"]
name = "cadquery"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.12,<3.14"
cadquery = "*"
fastapi = ">=0.128.0,<0.129"
uvicorn = ">=0.40.0,<0.41"
websockets = ">=16.0,<17"
